#!/bin/bash

python3.7 bertattack.py --alpha 0.0 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.25 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.50 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.75 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 1.0 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack_nli_p.py --alpha 0.0 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_p.py --alpha 0.25 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_p.py --alpha 0.50 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_p.py --alpha 0.75 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_p.py --alpha 1.0 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack_nli_h.py --alpha 0.0 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_h.py --alpha 0.25 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_h.py --alpha 0.50 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_h.py --alpha 0.75 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_h.py --alpha 1.0 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-base-cased --use_sim_mat 1 --output_dir data_defense/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack.py --alpha 0.0 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir data_defense/hate.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.25 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir data_defense/hate.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.50 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir data_defense/hate.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.75 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir data_defense/hate.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 1.0 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir data_defense/hate.tsv --num_label 3 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack_hate.py --alpha 0.0 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir data_defense/hate2.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_hate.py --alpha 0.25 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir data_defense/hate2.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_hate.py --alpha 0.50 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir data_defense/hate2.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_hate.py --alpha 0.75 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir data_defense/hate2.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_hate.py --alpha 1.0 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir data_defense/hate2.tsv --num_label 2 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack.py --alpha 0.0 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir data_defense/agnews.tsv --num_label 4 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.25 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir data_defense/agnews.tsv --num_label 4 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.50 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir data_defense/agnews.tsv --num_label 4 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 0.75 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir data_defense/agnews.tsv --num_label 4 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 1.0 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir data_defense/agnews.tsv --num_label 4 --use_bpe 1 --k 48 --start 0 --end 1000 --threshold_pred_score 0
