#!/bin/bash

python3.7 bertattack.py --alpha 0 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 25 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 50 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 75 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 100 --data_path data_defense/imdb_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-imdb --use_sim_mat 1 --output_dir alpha/imdb_logs.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack_nli_p.py --alpha 0 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_p.py --alpha 25 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_p.py --alpha 50 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_p.py --alpha 75 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_p.py --alpha 100 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_p_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack_nli_h.py --alpha 0 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_h_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_h.py --alpha 25 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_h_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_h.py --alpha 50 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_h_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_h.py --alpha 75 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_h_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_nli_h.py --alpha 100 --data_path data_defense/snli --mlm_path bert-base-uncased --tgt_path boychaboy/SNLI_bert-large-uncased --use_sim_mat 1 --output_dir alpha/snli_h_logs.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack.py --alpha 0 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir alpha/hate.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 25 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir alpha/hate.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 50 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir alpha/hate.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 75 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir alpha/hate.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 100 --data_path data_defense/HateXplain_test_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain --use_sim_mat 1 --output_dir alpha/hate.tsv --num_label 3 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack_hate.py --alpha 0 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir alpha/hate2.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_hate.py --alpha 25 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir alpha/hate2.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_hate.py --alpha 50 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir alpha/hate2.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_hate.py --alpha 75 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir alpha/hate2.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack_hate.py --alpha 100 --data_path data_defense/HateXplain_test_2_1k.tsv --mlm_path bert-base-uncased --tgt_path Hate-speech-CNERG/bert-base-uncased-hatexplain-rationale-two --use_sim_mat 1 --output_dir alpha/hate2.tsv --num_label 2 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0

python3.7 bertattack.py --alpha 0 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir alpha/agnews.tsv --num_label 4 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 25 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir alpha/agnews.tsv --num_label 4 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 50 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir alpha/agnews.tsv --num_label 4 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 75 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir alpha/agnews.tsv --num_label 4 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
python3.7 bertattack.py --alpha 100 --data_path data_defense/ag_1k.tsv --mlm_path bert-base-uncased --tgt_path fabriceyhc/bert-base-uncased-ag_news --use_sim_mat 1 --output_dir alpha/agnews.tsv --num_label 4 --use_bpe 1 --k 24 --start 0 --end 1000 --threshold_pred_score 0
